name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: update package manager & install python3 environment
        run: |
          pip install poetry
          poetry install

      - name: test
        run: poetry run pytest test